std::result::Result<instruction::EmergencyWithdraw, std::io::Error>
